# Generated by Django 6.0.4 on 2026-04-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
