# Generated by Django 6.0.1 on 2026-05-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_options_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
