# Generated by Django 6.0.1 on 2026-05-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
