# Generated by Django 6.0.1 on 2026-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_jobapplication_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
