# Generated by Django 6.0.1 on 2026-05-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_jobapplication_interview_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='applications.jobapplication')),
            ],
            options={
                'db_table': 'application_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
